<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
        'key' => 'group_58abfd3931f2f',
        'title' => 'Composite Fields',
        'fields' => array (
            array (
                'key' => 'field_58e388862daa8',
                'label' => 'Kind',
                'name' => 'kind',
                'type' => 'radio',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array (
                    'Article' => 'Article',
                    'Gallery' => 'Gallery',
                    'Story' => 'Story',
                    'Review' => 'Review',
                    'Recipe' => 'Recipe',
                ),
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => 'Article',
                'layout' => 'horizontal',
            ),
            array (
                'key' => 'field_58abfebd21b82',
                'label' => 'Description',
                'name' => 'description',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_58e39a7118284',
                'label' => 'Category',
                'name' => 'category',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'category',
                'field_type' => 'select',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 0,
                'return_format' => 'object',
                'multiple' => 0,
            ),
            array (
                'key' => 'field_58f606b6e1fb0',
                'label' => 'Tags',
                'name' => 'tags',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'post_tag',
                'field_type' => 'multi_select',
                'allow_null' => 0,
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 0,
                'return_format' => 'object',
                'multiple' => 0,
            ),
            array (
                'key' => 'field_58aae476809c6',
                'label' => 'Content (Widgets)',
                'name' => 'compositeContent',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'button_label' => 'Add Row',
                'min' => '',
                'max' => '',
                'layouts' => array (
                    array (
                        'key' => '58aae53c26608',
                        'name' => 'text_item',
                        'label' => 'Text',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58aae55326609',
                                'label' => 'body',
                                'name' => 'textitem_body',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58aaef9fb02bc',
                        'name' => 'image',
                        'label' => 'Image',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58aaefacb02bd',
                                'label' => 'trait',
                                'name' => 'image_trait',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Primary' => 'Primary',
                                    'Secondary' => 'Secondary',
                                    'Tertiary' => 'Tertiary',
                                ),
                                'default_value' => array (
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                                'disabled' => 0,
                                'readonly' => 0,
                            ),
                            array (
                                'key' => 'field_58aaefe5b02be',
                                'label' => 'copyright',
                                'name' => 'image_copyright',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_58aaf023b02bf',
                                'label' => 'teaser',
                                'name' => 'image_teaser',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_58aaf032b02c0',
                                'label' => 'caption',
                                'name' => 'image_caption',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_58aaf042b02c1',
                                'label' => 'url',
                                'name' => 'image_url',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58aae89d0f005',
                        'name' => 'insertedCode',
                        'label' => 'Inserted Code',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58aae8b00f006',
                                'label' => 'code',
                                'name' => 'inserted_code_code',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58aae479d3958',
                        'name' => 'infobox',
                        'label' => 'Infobox',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58aae4b6809c7',
                                'label' => 'title',
                                'name' => 'infobox_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_58aae4d4809c8',
                                'label' => 'body',
                                'name' => 'infobox_body',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58aaea63b12d2',
                        'name' => 'video',
                        'label' => 'Video',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58aaeb26b12d4',
                                'label' => 'caption',
                                'name' => 'video_caption',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_58aaeba6b12d5',
                                'label' => 'thumbnail_url',
                                'name' => 'video_thumbnail_url',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array (
                                'key' => 'field_58aaebd0b12d6',
                                'label' => 'service',
                                'name' => 'video_service',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Youtube' => 'Youtube',
                                    'Video23' => 'Video23',
                                    'Vimeo' => 'Vimeo',
                                ),
                                'default_value' => array (
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                                'disabled' => 0,
                                'readonly' => 0,
                            ),
                            array (
                                'key' => 'field_58aaebe0b12d7',
                                'label' => 'video_identifier',
                                'name' => 'video_video_identifier',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58e393a7128b3',
                        'name' => 'associatedComposite',
                        'label' => 'Sub Content',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58e393e0128b4',
                                'label' => 'composite',
                                'name' => 'composite',
                                'type' => 'relationship',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'post_type' => array (
                                    0 => 'contenthub_composite',
                                ),
                                'taxonomy' => array (
                                ),
                                'filters' => array (
                                    0 => 'search',
                                    1 => 'taxonomy',
                                ),
                                'elements' => '',
                                'min' => 0,
                                'max' => 1,
                                'return_format' => 'object',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58aeadaacbe5c',
                        'name' => 'inventory',
                        'label' => 'Inventory',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58e3971e4d277',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_58aeadcdcbe5d',
                                'label' => 'Inventory Items',
                                'name' => 'inventoryItems',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => '',
                                'max' => '',
                                'layout' => 'table',
                                'button_label' => 'Add Row',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_58aeae3fcbe61',
                                        'label' => 'Name',
                                        'name' => 'name',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'readonly' => 0,
                                        'disabled' => 0,
                                    ),
                                    array (
                                        'key' => 'field_58aeae4ccbe62',
                                        'label' => 'Value',
                                        'name' => 'value',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'readonly' => 0,
                                        'disabled' => 0,
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'contenthub_composite',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_58e38d7eca92e',
        'title' => 'Teaser',
        'fields' => array (
            array (
                'key' => 'field_58e38d86194e2',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_58e38da2194e3',
                'label' => 'Image',
                'name' => 'image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array (
                'key' => 'field_58e38dd0194e4',
                'label' => 'Body',
                'name' => 'body',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'wpautop',
                'readonly' => 0,
                'disabled' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'contenthub_composite',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_58f607ebb79e3',
        'title' => 'Magazine',
        'fields' => array (
            array (
                'key' => 'field_58f5febf3cb9c',
                'label' => 'Magazine Year',
                'name' => 'magazine_year',
                'type' => 'number',
                'instructions' => 'The magazine year ie. 2017 if the article was published in 2017',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 2017,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 1900,
                'max' => 3000,
                'step' => 1,
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_58e3878b2dc76',
                'label' => 'Magazine Issue',
                'name' => 'magazine_issue',
                'type' => 'number',
                'instructions' => 'The magazine issue ie. 01 for the first issue of a given year',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 1,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '01',
                'max' => 100,
                'step' => 1,
                'readonly' => 0,
                'disabled' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'contenthub_composite',
                ),
            ),
        ),
        'menu_order' => 2,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

endif;
