<?php

namespace Bonnier\WP\ContentHub\Editor\Models\ACF\Composite;
use Bonnier\WP\ContentHub\Editor\Models\WpComposite;

/**
 * Class CompositeFieldGroup
 *
 * @package \Bonnier\WP\ContentHub\Editor\Models\ACF\Composite
 */
class CompositeFieldGroup
{
    public static function register() {
        static::create_acf_field_group();
    }

    private static function create_acf_field_group() {
        if( function_exists('acf_add_local_field_group') ):

            acf_add_local_field_group(array (
                'key' => 'group_58abfd3931f2f',
                'title' => 'Composite Fields',
                'fields' => array (
                    array (
                        'key' => 'field_58e388862daa8',
                        'label' => 'Kind',
                        'name' => 'kind',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array (
                            'Article' => 'Article',
                            'Gallery' => 'Gallery',
                            'Story' => 'Story',
                            'Review' => 'Review',
                            'Recipe' => 'Recipe',
                        ),
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => 'Article',
                        'layout' => 'horizontal',
                        'allow_null' => 0,
                        'return_format' => 'value',
                    ),
                    array (
                        'key' => 'field_58abfebd21b82',
                        'label' => 'Description',
                        'name' => 'description',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array (
                        'key' => 'field_58e39a7118284',
                        'label' => 'Category',
                        'name' => 'category',
                        'type' => 'taxonomy',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'taxonomy' => 'category',
                        'field_type' => 'select',
                        'allow_null' => 0,
                        'add_term' => 0,
                        'save_terms' => 1,
                        'load_terms' => 0,
                        'return_format' => 'object',
                        'multiple' => 0,
                    ),
                    array (
                        'key' => 'field_58f606b6e1fb0',
                        'label' => 'Tags',
                        'name' => 'tags',
                        'type' => 'taxonomy',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'taxonomy' => 'post_tag',
                        'field_type' => 'multi_select',
                        'allow_null' => 0,
                        'add_term' => 1,
                        'save_terms' => 1,
                        'load_terms' => 0,
                        'return_format' => 'object',
                        'multiple' => 0,
                    ),
                    array (
                        'key' => 'field_5921f0c676974',
                        'label' => 'Locked Content',
                        'name' => 'locked_content',
                        'type' => 'true_false',
                        'instructions' => 'Check this box if you want parts of the content to be locked. Please note that you should mark each content item that you want to be locked by checking the "Locked Content" checkbox.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array (
                        'key' => 'field_5921f0e576975',
                        'label' => 'Required User Role',
                        'name' => 'required_user_role',
                        'type' => 'select',
                        'instructions' => 'Select the role required to access the locked parts of the content',
                        'required' => 0,
                        'conditional_logic' => array (
                            array (
                                array (
                                    'field' => 'field_5921f0c676974',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array (
                            'RegUser' => 'Registered User',
                            'Subscriber' => 'Subscriber',
                        ),
                        'default_value' => array (
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ),
                    array (
                        'key' => 'field_58aae476809c6',
                        'label' => 'Content (Widgets)',
                        'name' => 'composite_content',
                        'type' => 'flexible_content',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'button_label' => 'Add Widget',
                        'min' => '',
                        'max' => '',
                        'layouts' => array (
                            array (
                                'key' => '58aae53c26608',
                                'name' => 'text_item',
                                'label' => 'Text',
                                'display' => 'block',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_58aae55326609',
                                        'label' => 'Body',
                                        'name' => 'body',
                                        'type' => 'markdown-editor',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'simple_mde_config' => json_encode([
                                            'toolbar' => [
                                                'bold',
                                                'italic',
                                                'heading-2',
                                                'heading-3',
                                                '|',
                                                'unordered-list',
                                                'ordered-list',
                                                'link',
                                                '|',
                                                'preview',
                                                'guide'
                                            ]
                                        ]),
                                        'font_size' => 14,
                                    ),
                                    array (
                                        'key' => 'field_5922bd745cd9d',
                                        'label' => 'Locked Content',
                                        'name' => 'locked_content',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_5921f0c676974',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array (
                                'key' => '58aaef9fb02bc',
                                'name' => 'image',
                                'label' => 'Image',
                                'display' => 'block',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5908407c246cb',
                                        'label' => 'Lead Image',
                                        'name' => 'lead_image',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array (
                                        'key' => 'field_58aaf042b02c1',
                                        'label' => 'File',
                                        'name' => 'file',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'id',
                                        'preview_size' => 'thumbnail',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array (
                                        'key' => 'field_5922bd8e5cd9e',
                                        'label' => 'Locked Content',
                                        'name' => 'locked_content',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_5921f0c676974',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array (
                                'key' => '590aef9de4a5e',
                                'name' => 'file',
                                'label' => 'File',
                                'display' => 'block',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_590aefe3e4a5f',
                                        'label' => 'Caption',
                                        'name' => 'caption',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => '',
                                        'new_lines' => '',
                                    ),
                                    array (
                                        'key' => 'field_590af026e4a61',
                                        'label' => 'File',
                                        'name' => 'file',
                                        'type' => 'file',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'library' => 'all',
                                        'min_size' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array (
                                        'key' => 'field_5921e5a83f4ea',
                                        'label' => 'Images',
                                        'name' => 'images',
                                        'type' => 'repeater',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'collapsed' => '',
                                        'min' => 0,
                                        'max' => 0,
                                        'layout' => 'table',
                                        'button_label' => 'Add Image',
                                        'sub_fields' => array (
                                            array (
                                                'key' => 'field_5921e94c3f4eb',
                                                'label' => 'File',
                                                'name' => 'file',
                                                'type' => 'image',
                                                'instructions' => '',
                                                'required' => 1,
                                                'conditional_logic' => 0,
                                                'wrapper' => array (
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'return_format' => 'id',
                                                'preview_size' => 'thumbnail',
                                                'library' => 'all',
                                                'min_width' => '',
                                                'min_height' => '',
                                                'min_size' => '',
                                                'max_width' => '',
                                                'max_height' => '',
                                                'max_size' => '',
                                                'mime_types' => '',
                                            ),
                                        ),
                                    ),
                                    array (
                                        'key' => 'field_590af0eee4a62',
                                        'label' => 'Locked Content',
                                        'name' => 'locked_content',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_5921f0c676974',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array (
                                        'key' => 'field_59e49490911cf',
                                        'label' => 'Download Button Text (Optional)',
                                        'name' => 'download_button_text',
                                        'type' => 'text',
                                        'instructions' => 'This will override the default button text.',
                                        'required' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array (
                                'key' => '58aaea63b12d2',
                                'name' => 'video',
                                'label' => 'Video',
                                'display' => 'block',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5938fe71ed0bb',
                                        'label' => 'Embed Url',
                                        'name' => 'embed_url',
                                        'type' => 'text',
                                        'instructions' => 'Paste the embed url from your video provider, supported providers are: Vimeo, YouTube, 23Video',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_58aaeb26b12d4',
                                        'label' => 'Caption',
                                        'name' => 'caption',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => '',
                                        'new_lines' => '',
                                    ),
                                    array (
                                        'key' => 'field_5922be0e5cda4',
                                        'label' => 'Locked Content',
                                        'name' => 'locked_content',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_5921f0c676974',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array (
                                'key' => '590b1798c8768',
                                'name' => 'link',
                                'label' => 'Link',
                                'display' => 'block',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_590b17c4c876a',
                                        'label' => 'URL',
                                        'name' => 'url',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_590b179fc8769',
                                        'label' => 'Button text',
                                        'name' => 'title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_590b17d4c876b',
                                        'label' => 'Target',
                                        'name' => 'target',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array (
                                            'Default' => 'Default For the Site',
                                            'Self' => 'Open in same window/tab',
                                            'Blank' => 'Open in a new tab',
                                            'Download' => 'Force download a file',
                                        ),
                                        'default_value' => array (
                                            0 => 'Default',
                                        ),
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'return_format' => 'value',
                                        'placeholder' => '',
                                    ),
                                    array (
                                        'key' => 'field_5922be3e5cda5',
                                        'label' => 'Locked Content',
                                        'name' => 'locked_content',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_5921f0c676974',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array (
                                'key' => '5a4f4dea1745f',
                                'name' => 'gallery',
                                'label' => 'Gallery',
                                'display' => 'block',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5a4f4dfd17460',
                                        'label' => 'Images',
                                        'name' => 'images',
                                        'type' => 'repeater',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'collapsed' => '',
                                        'min' => 0,
                                        'max' => 0,
                                        'layout' => 'block',
                                        'button_label' => 'Add Image to Gallery',
                                        'sub_fields' => array (
                                            array (
                                                'key' => 'field_5a4f4e0f17461',
                                                'label' => 'Image',
                                                'name' => 'image',
                                                'type' => 'image',
                                                'instructions' => '',
                                                'required' => 1,
                                                'conditional_logic' => 0,
                                                'wrapper' => array (
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'return_format' => 'id',
                                                'preview_size' => 'thumbnail',
                                                'library' => 'all',
                                                'min_width' => '',
                                                'min_height' => '',
                                                'min_size' => '',
                                                'max_width' => '',
                                                'max_height' => '',
                                                'max_size' => '',
                                                'mime_types' => '',
                                            ),
                                        ),
                                    ),
                                    array (
                                        'key' => 'field_5a4f4e5f17462',
                                        'label' => 'Locked Content',
                                        'name' => 'locked_content',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_5921f0c676974',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array (
                                'key' => '58aae89d0f005',
                                'name' => 'inserted_code',
                                'label' => 'Inserted Code',
                                'display' => 'block',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_58aae8b00f006',
                                        'label' => 'Code',
                                        'name' => 'code',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => '',
                                        'new_lines' => '',
                                    ),
                                    array (
                                        'key' => 'field_5922bdbd5cda1',
                                        'label' => 'Locked Content',
                                        'name' => 'locked_content',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_5921f0c676974',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array (
                                'key' => '58aae479d3958',
                                'name' => 'infobox',
                                'label' => 'Infobox',
                                'display' => 'block',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_58aae4b6809c7',
                                        'label' => 'Title',
                                        'name' => 'title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_58aae4d4809c8',
                                        'label' => 'Body',
                                        'name' => 'body',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => '',
                                        'new_lines' => '',
                                    ),
                                    array (
                                        'key' => 'field_5922bdd55cda2',
                                        'label' => 'Locked Content',
                                        'name' => 'locked_content',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_5921f0c676974',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array (
                                'key' => '58e393a7128b3',
                                'name' => 'associated_composite',
                                'label' => 'Sub Content',
                                'display' => 'block',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_58e393e0128b4',
                                        'label' => 'Content',
                                        'name' => 'composite',
                                        'type' => 'relationship',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'post_type' => array (
                                            0 => 'contenthub_composite',
                                        ),
                                        'taxonomy' => array (
                                        ),
                                        'filters' => array (
                                            0 => 'search',
                                            1 => 'taxonomy',
                                        ),
                                        'elements' => '',
                                        'min' => '',
                                        'max' => 1,
                                        'return_format' => 'object',
                                    ),
                                    array (
                                        'key' => 'field_5922be585cda6',
                                        'label' => 'Locked Content',
                                        'name' => 'locked_content',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_5921f0c676974',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            array (
                                'key' => '58aeadaacbe5c',
                                'name' => 'inventory',
                                'label' => 'Inventory',
                                'display' => 'block',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_58e3971e4d277',
                                        'label' => 'Title',
                                        'name' => 'title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'readonly' => 0,
                                        'disabled' => 0,
                                    ),
                                    array (
                                        'key' => 'field_58aeadcdcbe5d',
                                        'label' => 'Inventory Items',
                                        'name' => 'inventory_items',
                                        'type' => 'repeater',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'collapsed' => '',
                                        'min' => 0,
                                        'max' => 0,
                                        'layout' => 'table',
                                        'button_label' => 'Add Row',
                                        'sub_fields' => array (
                                            array (
                                                'key' => 'field_58aeae3fcbe61',
                                                'label' => 'Name',
                                                'name' => 'name',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 1,
                                                'conditional_logic' => 0,
                                                'wrapper' => array (
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => '',
                                                'readonly' => 0,
                                                'disabled' => 0,
                                            ),
                                            array (
                                                'key' => 'field_58aeae4ccbe62',
                                                'label' => 'Value',
                                                'name' => 'value',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array (
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => '',
                                                'readonly' => 0,
                                                'disabled' => 0,
                                            ),
                                        ),
                                    ),
                                    array (
                                        'key' => 'field_5922be6d5cda7',
                                        'label' => 'Locked Content',
                                        'name' => 'locked_content',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_5921f0c676974',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => '',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                        ),
                    ),
                ),
                'location' => array (
                    array (
                        array (
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => WpComposite::POST_TYPE,
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'acf_after_title',
                'style' => 'seamless',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => array (
                    0 => 'categories',
                ),
                'active' => 1,
                'description' => '',
            ));
        endif;

    }
}
