<?php

namespace Bonnier\WP\ContentHub\Editor\Tests\wpunit\ACF;

use Bonnier\WP\ContentHub\Editor\Models\ACF\Composite\MetaFieldGroup;
use PHPUnit\Framework\TestCase;

class MetaFieldGroupTest extends TestCase
{
    public function testACFStructure()
    {
        $expected = [
            'key' => 'group_58fde819ea0f1',
            'title' => 'Meta',
            'fields' => [
                [
                    'key' => 'field_5af188bbb5b45',
                    'label' => 'Canonical URL',
                    'name' => 'canonical_url',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_58fde84d034e4',
                    'label' => 'Commercial',
                    'name' => 'commercial',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ],
                [
                    'key' => 'field_58fde876034e5',
                    'label' => 'Commercial Type',
                    'name' => 'commercial_type',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => [
                        [
                            [
                                'field' => 'field_58fde84d034e4',
                                'operator' => '==',
                                'value' => '1',
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'choices' => [
                        'Advertorial' => 'Advertorial',
                        'AffiliatePartner' => 'AffiliatePartner',
                        'CommercialContent' => 'CommercialContent',
                        'Offer' => 'Offer',
                    ],
                    'default_value' => [
                    ],
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_5a8d72d39ee48',
                    'label' => 'Commercial logo',
                    'name' => 'commercial_logo',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => [
                        [
                            [
                                'field' => 'field_58fde84d034e4',
                                'operator' => '==',
                                'value' => '1',
                            ],
                        ],
                    ],
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'return_format' => 'id',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'thumbnail',
                    'min_width' => '',
                    'min_height' => '',
                    'max_width' => '',
                    'max_height' => '',
                ],
                [
                    'key' => 'field_58fde876034e6',
                    'label' => 'Internal Comment',
                    'name' => 'internal_comment',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => 3,
                    'new_lines' => '',
                ],
                [
                    'key' => 'field_58f5febf3cb9c',
                    'label' => 'Magazine Year',
                    'name' => 'magazine_year',
                    'type' => 'select',
                    'instructions' => 'The magazine year ie. 2017 if the article was published in 2017',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'choices' => MetaFieldGroup::getYears(),
                    'default_value' => [],
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_58e3878b2dc76',
                    'label' => 'Magazine Issue',
                    'name' => 'magazine_issue',
                    'type' => 'select',
                    'instructions' => 'The magazine issue ie. 01 for the first issue of a given year',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'choices' => MetaFieldGroup::getIssues(),
                    'default_value' => [],
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_5bb4abe52f3d7',
                    'label' => 'Audio',
                    'name' => 'audio',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'layout' => 'block',
                    'sub_fields' => [
                        [
                            'key' => 'field_5bb4ac792f3d8',
                            'label' => 'File',
                            'name' => 'file',
                            'type' => 'file',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'return_format' => 'id',
                            'library' => 'all',
                            'min_size' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ],
                        [
                            'key' => 'field_5bb4aca02f3d9',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ],
                        [
                            'key' => 'field_5bb4acb12f3da',
                            'label' => 'Audio Thumbnail',
                            'name' => 'audio_thumbnail',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => [
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ],
                            'return_format' => 'id',
                            'library' => 'all',
                            'min_size' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'preview_size' => 'thumbnail',
                            'min_width' => '',
                            'min_height' => '',
                            'max_width' => '',
                            'max_height' => '',
                        ],
                    ]
                ]
            ],
            'location' => [
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'contenthub_composite',
                    ],
                ],
            ],
            'menu_order' => 4,
            'position' => 'side',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ];
        $actual = MetaFieldGroup::getFieldGroup();

        $this->assertSame($expected, $actual);
    }
}
