<?php

namespace Bonnier\WP\ContentHub\Editor\Tests\wpunit\ACF;

use Bonnier\WP\ContentHub\Editor\Models\ACF\Composite\TeaserFieldGroup;
use PHPUnit\Framework\TestCase;

class TeaserFieldGroupTest extends TestCase
{
    public function testACFStructure()
    {
        $expected = [
            'key' => 'group_58e38d7eca92e',
            'title' => 'Teasers',
            'fields' => [
                [
                    'key' => 'field_5aeac69f22931',
                    'label' => 'Site Teaser (Eg. article teasers, search results, cxense etc.)',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_58e38d86194e2',
                    'label' => 'Teaser Title',
                    'name' => 'teaser_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ],
                [
                    'key' => 'field_58e38da2194e3',
                    'label' => 'Teaser Image',
                    'name' => 'teaser_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'return_format' => 'id',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'thumbnail',
                    'min_width' => '',
                    'min_height' => '',
                    'max_width' => '',
                    'max_height' => '',
                ],
                [
                    'key' => 'field_58e38dd0194e4',
                    'label' => 'Teaser Description',
                    'name' => 'teaser_description',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                ],
                [
                    'key' => 'field_5aeac72bfaaf1',
                    'label' => 'SEO Teaser (Google)',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_5aeac749faaf2',
                    'label' => 'Teaser Title',
                    'name' => 'seo_teaser_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ],
                [
                    'key' => 'field_5aeac77c8d9cf',
                    'label' => 'Teaser Image',
                    'name' => 'seo_teaser_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'return_format' => 'id',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'thumbnail',
                    'min_width' => '',
                    'min_height' => '',
                    'max_width' => '',
                    'max_height' => '',
                ],
                [
                    'key' => 'field_5aeac79e8d9d0',
                    'label' => 'Teaser Description',
                    'name' => 'seo_teaser_description',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                ],
                [
                    'key' => 'field_5aeac7e96eb57',
                    'label' => 'Facebook Teaser',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_5aeac8356eb58',
                    'label' => 'Teaser Title',
                    'name' => 'fb_teaser_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ],
                [
                    'key' => 'field_5aeac8476eb59',
                    'label' => 'Teaser Image',
                    'name' => 'fb_teaser_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'return_format' => 'id',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'thumbnail',
                    'min_width' => '',
                    'min_height' => '',
                    'max_width' => '',
                    'max_height' => '',
                ],
                [
                    'key' => 'field_5aeac8546eb5a',
                    'label' => 'Teaser Description',
                    'name' => 'fb_teaser_description',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                ],
                [
                    'key' => 'field_5aeac86e39537',
                    'label' => 'Twitter Teaser',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'placement' => 'top',
                    'endpoint' => 0,
                ],
                [
                    'key' => 'field_5aeac87839538',
                    'label' => 'Teaser Title',
                    'name' => 'tw_teaser_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ],
                [
                    'key' => 'field_5aeac88039539',
                    'label' => 'Teaser Image',
                    'name' => 'tw_teaser_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'return_format' => 'id',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'thumbnail',
                    'min_width' => '',
                    'min_height' => '',
                    'max_width' => '',
                    'max_height' => '',
                ],
                [
                    'key' => 'field_5aeac88c3953a',
                    'label' => 'Teaser Description',
                    'name' => 'tw_teaser_description',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'contenthub_composite',
                    ],
                ],
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'page',
                    ],
                ],
            ],
            'menu_order' => 1,
            'position' => 'acf_after_title',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ];

        $actual = TeaserFieldGroup::getFieldGroup();
        $this->assertSame($expected, $actual);
    }
}
